use_frameworks!

platform :ios, '8.0'

target 'SimpleMarkdownParser_Example' do
  pod 'SimpleMarkdownParser', :path => '../../'

  target 'SimpleMarkdownParser_Tests' do
    inherit! :search_paths
    pod 'SimpleMarkdownParser', :path => '../../'
  end
end
